#!/usr/bin/env python3

from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT_FILE = SCRIPT_DIR.parent / "loadouts" / "data" / "loadouts" / "functions" / "extra" / "junk_clear.mcfunction"

ALLOWED_ITEMS = [
    # Vanilla
    "minecraft:cooked_beef",
    "minecraft:dirt",
    "minecraft:netherite_pickaxe",
    "minecraft:obsidian",
    "minecraft:beacon",

    # Vehicles
    "mcsp:bmd_4_camo_spawn_item",
    "mcsp:humvee_desert_standart_spawn_item",
    "mcsp:m1a2_sep_sand_spawn_item",
    "mcsp:m1a2_sep_spawn_item",
    "mcsp:m3a3_bradley_busk_iii_sand_spawn_item",
    "mcsp:m3a3_bradley_busk_iii_spawn_item",
    "mcsp:sprut_camo_spawn_item",
    "mcsp:vdv_desert_30mm_spawn_item",

    # Walkie talkie
    "walkietalkie:netherite_walkietalkie",

    # SuperbWarfare weapons & consumables
    "superbwarfare:aa_12",
    "superbwarfare:ak_12",
    "superbwarfare:ak_47",
    "superbwarfare:awm",
    "superbwarfare:sks",
    "superbwarfare:devotion",
    "superbwarfare:glock_18",
    "superbwarfare:hk_416",
    "superbwarfare:insidious",
    "superbwarfare:javelin",
    "superbwarfare:k_98",
    "superbwarfare:m_1911",
    "superbwarfare:m_2_hb",
    "superbwarfare:m_4",
    "superbwarfare:m_60",
    "superbwarfare:m_79",
    "superbwarfare:m_870",
    "superbwarfare:m_98b",
    "superbwarfare:marlin",
    "superbwarfare:minigun",
    "superbwarfare:mk_14",
    "superbwarfare:mortar_deployer",
    "superbwarfare:mosin_nagant",
    "superbwarfare:mp_443",
    "superbwarfare:mp_5",
    "superbwarfare:ntw_20",
    "superbwarfare:qbz_191",
    "superbwarfare:qbz_95",
    "superbwarfare:rpg",
    "superbwarfare:rpk",
    "superbwarfare:sentinel",
    "superbwarfare:svd",
    "superbwarfare:vector",
    "superbwarfare:igla_9k38",
    "superbwarfare:trachelium",
    "superbwarfare:ap_5_inches",
    "superbwarfare:armor_plate",
    "superbwarfare:artillery_indicator",
    "superbwarfare:blu_43_mine",
    "superbwarfare:c4_bomb",
    "superbwarfare:claymore_mine",
    "superbwarfare:detonator",
    "superbwarfare:drone",
    "superbwarfare:grenade_40mm",
    "superbwarfare:hand_grenade",
    "superbwarfare:handgun_ammo",
    "superbwarfare:he_5_inches",
    "superbwarfare:heavy_ammo",
    "superbwarfare:igla_9k38_missile",
    "superbwarfare:javelin_missile",
    "superbwarfare:large_battery_pack",
    "superbwarfare:m18_smoke_grenade",
    "superbwarfare:medical_kit",
    "superbwarfare:monitor",
    "superbwarfare:mortar_shell",
    "superbwarfare:parachute",
    "superbwarfare:rgo_grenade",
    "superbwarfare:rifle_ammo",
    "superbwarfare:rpg_rocket_tbg",
    "superbwarfare:shotgun_ammo",
    "superbwarfare:small_shell",
    "superbwarfare:small_rocket",
    "superbwarfare:sniper_ammo",
    "superbwarfare:tm_62",
    "superbwarfare:wire_guide_missile",
    "superbwarfare:medium_rocket_ap",
    "superbwarfare:medium_rocket_he",
    "superbwarfare:medium_rocket_cm",
    "superbwarfare:knife",
    "superbwarfare:container",
    "superbwarfare:crowbar",
    "superbwarfare:agm",
    "superbwarfare:medium_aerial_bomb",

    # AshVehicles
    "ashvehicle:aam_4_item",
    "ashvehicle:gbu-57-item",
    "ashvehicle:jassm_item",

    # Armor
    "superbwarfare:ru_chest_6b43",
    "superbwarfare:ru_helmet_6b47",
    "superbwarfare:us_chest_iotv",
    "superbwarfare:us_helmet_pastg",
    "mcsp:vest_avs",
    "mcsp:opscore_helmet",
    "exoskeleton:exo_helmet",
    "thermal_imaging_goggles:thermal_imaging_goggles_helmet",
]

MAIN_SLOTS = list(range(36))
ARMOR_SLOTS = {
    100: "armor.feet",
    101: "armor.legs",
    102: "armor.chest",
    103: "armor.head",
}
OFFHAND_SLOT = -106

def build_line(inv_slot: int, target: str) -> str:
    conditions = "".join(
        f' unless data entity @s Inventory[{{Slot:{inv_slot}b,id:"{item}"}}]'
        for item in ALLOWED_ITEMS
    )
    return f"execute{conditions} run item replace entity @s {target} with air"

def main():
    lines = ["# Auto-generated by generate_junk_clear.py - do not hand-edit, re-run the script instead", ""]

    lines.append("# Main inventory (hotbar + storage)")
    for slot in MAIN_SLOTS:
        lines.append(build_line(slot, f"container.{slot}"))

    lines.append("")
    lines.append("# Armor slots")
    for inv_slot, target in ARMOR_SLOTS.items():
        lines.append(build_line(inv_slot, target))

    lines.append("")
    lines.append("# Offhand")
    lines.append(build_line(OFFHAND_SLOT, "weapon.offhand"))

    lines.append("")
    lines.append('tellraw @s {"text":"[✔] Inventory cleaned!","color":"green"}')
    lines.append("playsound minecraft:entity.experience_orb.pickup master @s ~ ~ ~ 1 1")

    OUTPUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Wrote {OUTPUT_FILE} ({len(lines)} lines, {len(ALLOWED_ITEMS)} allowed items)")

if __name__ == "__main__":
    main()
