#!/usr/bin/env python3

from pathlib import Path

RADIUS = 4

SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = SCRIPT_DIR.parent / "loadouts" / "data" / "loadouts" / "functions" / "admin" / "warzone"

def gen(team: str) -> str:
    lines = [f"# Auto-generated by generate_beacon_scan.py - locates the {team} beacon"]
    lines.append("scoreboard players set #wz_scan_done temp_count 0")
    lines.append("")
    for dx in range(-RADIUS, RADIUS + 1):
        for dy in range(-RADIUS, RADIUS + 1):
            for dz in range(-RADIUS, RADIUS + 1):
                lines.append(
                    f"execute if score #wz_scan_done temp_count matches 0 "
                    f"positioned ~{dx} ~{dy} ~{dz} align xyz "
                    f"if block ~ ~ ~ minecraft:beacon "
                    f"run function loadouts:admin/warzone/{team}_cell_found"
                )
    return "\n".join(lines) + "\n"

for team in ("red", "blue"):
    out_file = OUTPUT_DIR / f"locate_{team}_beacon.mcfunction"
    out_file.write_text(gen(team))
    print(f"wrote {out_file}")
